language: java
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - MODULE=1.7.10
#    - MODULE=core

before_install: chmod +x gradlew
install:
  - git clone -b $TRAVIS_BRANCH https://github.com/NOVAAPI/NovaCore/ || git clone https://github.com/NOVAAPI/NovaCore/
script:
  - ./gradlew -Pnova.core.location=NovaCore/ --continue :${MODULE}:check :${MODULE}:javadoc :${MODULE}:jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - cd ~/.gradle; find . -maxdepth 1 -type d -not -name 'caches' -not -name 'wrapper' -not -name '.' -exec rm -vRf {} \;;cd -
  - find ~/.gradle/ -type f -name *.lock -delete
  - rm -Rf ~/.gradle/caches/*/scripts
cache:
  directories:
  - ~/.gradle

notifications:
  email: false
