language: java
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - MODULE=1.7.10
#    - MODULE=core

before_install: chmod +x gradlew
install:
  - git clone https://github.com/NOVAAPI/NovaCore/
script:
  - ./gradlew -Pnova.core.location=NovaCore/ --continue :${MODULE}:check :${MODULE}:javadoc :${MODULE}:jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - find ~/.gradle/ -name *.lock -print0 | xargs -0 rm -f

cache:
  directories:
  - ~/.gradle

notifications:
  irc:
    channels:
      - "irc.esper.net#NovaAPI"
    on_success: change
    on_failure: always
    skip_join: true
  email: false
