language: java
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - MODULE=1.7.10
#    - MODULE=core

before_install: chmod +x gradlew
install:
  - git clone https://github.com/NOVAAPI/NovaCore/
script:
  - ./gradlew -Pnova.core.location=NovaCore/ --continue :${MODULE}:check :${MODULE}:javadoc :${MODULE}:jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - find -maxdepth 1 ~/.gradle/ -type d -not -name 'caches' -not -name 'wrapper' -not -name '.' -exec rm -Rf {}
  - find ~/.gradle/ -type f -name *.lock -delete
cache:
  directories:
  - ~/.gradle

notifications:
  email: false
